
module.exports = [
    {
        id: "b70067d1-49c9-4925-b830-67b3e98005d5",
        event_name: "Neon Horizon",
        event_date: "2024-05-15",
        venue_id: '2922c286-16cd-4d43-ab98-c79f698aeab0',
        start_time: "20:00:00",
        sell_through: 0.85,
        ticket_price: 55.00,
        ticket_price_currency: "GBP",
        event_desc: "Neon Horizon redefines electronic music, blending pulsating beats with ethereal melodies, crafting sonic landscapes that mesmerize. Experience their electrifying performance at Toronto's Massey Hall.",
        event_image: "https://ik.imagekit.io/enxdlva/event-images/takemeout/marcela-laskoski-YrtFlrLo2DQ-unsplash.jpg",
        event_image_attribution: "Marcela Laskoski",
        event_image_attribution_link: "https://unsplash.com/@marcelalaskoski?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash"
    },
    {
        id: "7c79d334-6b90-4052-9def-aa9b8519c9fb",
        event_name: "Velvet Echo",
        event_date: "2024-06-07",
        venue_id: '5bf7bd6c-2b16-4129-bddc-9d37ff8539e9',
        start_time: "19:30:00",
        sell_through: 0.90,
        ticket_price: 60.00,
        ticket_price_currency: "GBP",
        event_desc: "Prepare to be swept away by the enchanting sounds of Velvet Echo. Lose yourself in a mesmerizing fusion of smooth melodies and soulful rhythms in the heart of Quebec's vibrant metropolis.",
        event_image: "https://ik.imagekit.io/enxdlva/event-images/takemeout/caleb-george-pH88tHG-1yw-unsplash.jpg",
        event_image_attribution: "Caleb George",
        event_image_attribution_link: "https://unsplash.com/@seemoris?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash"
    },
    {
        id: "eafcb711-a726-4b3c-adec-704e3265c47d",
        event_name: "Mirage",
        event_date: "2024-07-20",
        venue_id: '90ac3319-70d1-4a51-b91d-ba6c2464408c',
        start_time: "19:00:00",
        sell_through: 0.80,
        ticket_price: 50.00,
        ticket_price_currency: "GBP",
        event_desc: "Journey into the night with Mirage at the Scotiabank Centre in Halifax. Let the ethereal tunes of this captivating band transport you to a world where dreams meet reality.",
        event_image: "https://ik.imagekit.io/enxdlva/event-images/takemeout/daniel-wirtz-jmmTlAPtNw8-unsplash.jpg",
        event_image_attribution: "Daniel Wirtz",
        event_image_attribution_link: "https://unsplash.com/@danielwirtz?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash"
    },
    {
        id: "72c826ba-fde0-4aae-9aaf-95c6072946cd",
        event_name: "Electric Dreamers",
        event_date: "2024-08-10",
        venue_id: 'bfc9bea7-66f1-44e9-879b-4d363a888eb4',
        start_time: "20:30:00",
        sell_through: 0.95,
        ticket_price: 65.00,
        ticket_price_currency: "GBP",
        event_desc: "Immerse yourself in the dreamy atmosphere of Electric Dreamers at Rogers Arena. Surrender to the enchanting soundscape crafted by this dynamic band against the backdrop of British Columbia's stunning coastal city.",
        event_image: "https://ik.imagekit.io/enxdlva/event-images/takemeout/austin-neill-_uzJEiPETvY-unsplash.jpg",
        event_image_attribution: "Austin Neill",
        event_image_attribution_link: "https://unsplash.com/@arstyy?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash"
    },
    {
        id: "019da03d-1162-48a4-ad48-ed655e3d7301",
        event_name: "Echoes",
        event_date: "2024-06-22",
        venue_id: '89898957-04ba-4bd0-9f5c-a7aea7447963',
        start_time: "19:30:00",
        sell_through: 0.90,
        ticket_price: 70.00,
        ticket_price_currency: "GBP",
        event_desc: "Experience audio euphoria with Echoes at the Scotiabank Arena in Toronto. Their harmonious melodies promise an evening of pure musical bliss.",
        event_image: "https://ik.imagekit.io/enxdlva/event-images/takemeout/austin-neill-sxxnM-tRlVg-unsplash.jpg",
        event_image_attribution: "Austin Neill",
        event_image_attribution_link: "https://unsplash.com/@arstyy?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash"
    },
    {
        id: "705b808f-d8a0-4713-a796-8653c5c5952b",
        event_name: "Aurora Borealis",
        event_date: "2024-08-15",
        venue_id: 'ade0a47b-cee6-4693-b4cd-a7e6cb25f4b7',
        start_time: "20:00:00",
        sell_through: 0.85,
        ticket_price: 60.00,
        ticket_price_currency: "GBP",
        event_desc: "Witness the breathtaking spectacle of Aurora Borealis at Bell MTS Place in Winnipeg. Lose yourself in their ethereal melodies as they illuminate the night with their spellbinding performance.",
        event_image: "https://ik.imagekit.io/enxdlva/event-images/takemeout/jorge-zapata-ajLlK5qL6Ic-unsplash.jpg",
        event_image_attribution: "Jorge Zapata",
        event_image_attribution_link: "https://unsplash.com/@jorgezapatag?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash"
    },
    {
        id: "f19b0b8a-9cca-4567-9af7-4016a15e038a",
        event_name: "Dreamwave",
        event_date: "2024-09-08",
        venue_id: '90ac3319-70d1-4a51-b91d-ba6c2464408c',
        start_time: "19:00:00",
        sell_through: 0.80,
        ticket_price: 45.00,
        ticket_price_currency: "GBP",
        event_desc: "Feel the heat rise with Dreamwave at the Scotiabank Centre in Halifax. Get ready for an adrenaline-fueled night as this dynamic band ignites the stage, promising an unforgettable experience.",
        event_image: "https://ik.imagekit.io/enxdlva/event-images/takemeout/toa-heftiba-MRvBKn_ZlMM-unsplash.jpg",
        event_image_attribution: "Toa Heftiba",
        event_image_attribution_link: "https://unsplash.com/@heftiba?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash"
    },
    {
        id: "2cba0296-c77d-4758-9115-bd98ac18f2c0",
        event_name: "Wildfire Symphony",
        event_date: "2024-10-12",
        venue_id: 'bb1491eb-30e6-4728-a5fa-72f89feaf622',
        start_time: "20:00:00",
        sell_through: 0.85,
        ticket_price: 55.00,
        ticket_price_currency: "GBP",
        event_desc: "Get swept away by the orchestral grandeur of this dynamic ensemble. Wildfire Symphony promises a fiery performance in Canada's capital.",
        event_image: "https://ik.imagekit.io/enxdlva/event-images/takemeout/alex-padurariu-WypHPk6lBFQ-unsplash.jpg",
        event_image_attribution: "Alex Padurariu",
        event_image_attribution_link: "https://unsplash.com/@alexpadurariu?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash"
    },
    {
        id: "e202e167-d242-4d7f-b8fc-68caffef9e01",
        event_name: "Electric Pulse",
        event_date: "2024-11-05",
        venue_id: '150a36cf-f38e-4f59-8e31-39974207372d',
        start_time: "19:00:00",
        sell_through: 0.88,
        ticket_price: 75.00,
        ticket_price_currency: "GBP",
        event_desc: "Feel the pulse of the city with Electric Pulse at the Scotiabank Arena in Toronto. Join the rhythmic journey of this electrifying band as they promise an unforgettable evening.",
        event_image: "https://ik.imagekit.io/enxdlva/event-images/takemeout/matt-palmer-XLAeDbI52Ek-unsplash.jpg",
        event_image_attribution: "Matt Palmer",
        event_image_attribution_link: "https://unsplash.com/@mattpalmer?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash"
    },
    {
        id: "079c88df-ed32-4d88-a9b7-eaebc85c4ce2",
        event_name: "Sirens",
        event_date: "2024-12-20",
        venue_id: '9b4f79ea-0e6c-4e59-8e05-afd933d0b3d3',
        start_time: "20:00:00",
        sell_through: 0.85,
        ticket_price: 70.00,
        ticket_price_currency: "GBP",
        event_desc: "Sirens blends rock, folk, and soul, delivering powerful melodies and evocative lyrics. Dive into their emotional journey at Vogue Theatre for an unforgettable experience in Vancouver.",
        event_image: "https://ik.imagekit.io/enxdlva/event-images/takemeout/eric-nopanen-8e0EHPUx3Mo-unsplash.jpg?updatedAt=1714317514277",
        event_image_attribution: "Eric Nopanen",
        event_image_attribution_link: "https://unsplash.com/@rexcuando?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash"
    },
    {
        id: "56c8e94c-777d-4176-b7fd-02f0806f614a",
        event_name: "Solaris",
        event_date: "2025-01-15",
        venue_id: '90ac3319-70d1-4a51-b91d-ba6c2464408c',
        start_time: "19:30:00",
        sell_through: 0.90,
        ticket_price: 60.00,
        ticket_price_currency: "GBP",
        event_desc: "Immerse yourself in the sounds of Solaris at the Scotiabank Centre in Halifax. Journey through the cosmos with this captivating band as they weave a tapestry of melodies under the starry skies of Nova Scotia.",
        event_image: "https://ik.imagekit.io/enxdlva/event-images/takemeout/anthony-delanoix-hzgs56Ze49s-unsplash.jpg",
        event_image_attribution: "Anthony Delanoix",
        event_image_attribution_link: "https://unsplash.com/@anthonydelanoix?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash"
    },
    {
        id: "2c0185c7-89ef-48ad-a22f-9fc022a5c90c",
        event_name: "Cascade Beats",
        event_date: "2025-03-10",
        venue_id: "bb1491eb-30e6-4728-a5fa-72f89feaf622",
        start_time: "19:00:00",
        sell_through: 0.88,
        ticket_price: 65.00,
        ticket_price_currency: "GBP",
        event_desc: "Dive into a world of rhythm and melody with Cascade Beats, promising a thrilling performance in Canada's capital.",
        event_image: "https://ik.imagekit.io/enxdlva/event-images/takemeout/chris-zhang-uGh-hHVPRYI-unsplash.jpg",
        event_image_attribution: "Chris Zhang",
        event_image_attribution_link: "https://unsplash.com/@chriszhang0806?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash"
    },
    {
        id: "f3e13429-b5e9-4a50-b01c-75fb07cefded",
        event_name: "Stellar",
        event_date: "2024-09-05",
        venue_id: "83433026-ca32-4c6d-bd86-a39ee8b7303e",
        start_time: "19:00:00",
        sell_through: 0.90,
        ticket_price: 50.00,
        ticket_price_currency: "GBP",
        event_desc: "Stellar delivers electrifying energy and soulful melodies on stage. Don't miss their upcoming London show for powerful riffs and an unforgettable performance!",
        event_image: "https://ik.imagekit.io/enxdlva/event-images/takemeout/yannis-papanastasopoulos-yWF2LLan-_o-unsplash.jpg",
        event_image_attribution: "Yannis Papanastasopoulos",
        event_image_attribution_link: "https://unsplash.com/@yannispap?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash"
    },
    {
        id: "3b042051-f18c-4a16-a393-68ceba87277a",
        event_name: "Tides",
        event_date: "2024-10-18",
        venue_id: "a193a6a7-42ab-4182-97dc-555ee85e7486",
        start_time: "20:00:00",
        sell_through: 0.85,
        ticket_price: 45.00,
        ticket_price_currency: "GBP",
        event_desc: "Tides storms in with thunderous hard rock riffs, delivering raw energy and fierce stage presence. With a tidal wave of sound, Tides promises an unforgettable experience that will shake you to the core.",
        event_image: "https://ik.imagekit.io/enxdlva/event-images/takemeout/melanie-van-leeuwen-QA-qQfWJM0E-unsplash.jpg",
        event_image_attribution: "Melanie van Leeuwen",
        event_image_attribution_link: "https://unsplash.com/@strompictures?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash"
    },
    {
        id: "4d6ce289-eb58-45a1-bae3-e3874290ee48",
        event_name: "Lilies",
        event_date: "2024-11-12",
        venue_id: "8f16bd30-bab5-40af-aca2-b63d5fdd1acc",
        start_time: "19:30:00",
        sell_through: 0.95,
        ticket_price: 55.00,
        ticket_price_currency: "GBP",
        event_desc: "Lilies melds folk and pop, weaving delicate melodies and heartfelt lyrics. Their music evokes emotion, guiding listeners through love, longing, and introspection. Experience their captivating harmonies live in London.",
        event_image: "https://ik.imagekit.io/enxdlva/event-images/takemeout/te-nguyen-Wt7XT1R6sjU-unsplash.jpg",
        event_image_attribution: "Te NGuyen",
        event_image_attribution_link: "https://unsplash.com/@tenguyen?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash"
    },
    {
        id: "d3c08f85-4570-48e1-88df-610614477359",
        event_name: "Supernova",
        event_date: "2024-12-20",
        venue_id: "4dd464d6-90b8-4330-91e0-bd1217811bd9",
        start_time: "20:30:00",
        sell_through: 0.85,
        ticket_price: 50.00,
        ticket_price_currency: "GBP",
        event_desc: "Supernova, master of electronic beats, fuels dance floors with energy. With catchy rhythms and infectious melodies, prepare for a journey as every track ignites the night. Get ready for an unforgettable experience!",
        event_image: "https://ik.imagekit.io/enxdlva/event-images/takemeout/austin-neill-hgO1wFPXl3I-unsplash.jpg",
        event_image_attribution: "Austin Neill",
        event_image_attribution_link: "https://unsplash.com/@arstyy?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash"
    },
    {
        id: "043a70e2-cf28-4ce1-a9a4-e5b3fac9c593",
        event_name: "Electric Symphony",
        event_date: "2025-04-05",
        venue_id: "c0ba64a8-0ecb-4a7d-ab7f-2dbbd1d437b1",
        start_time: "19:30:00",
        sell_through: 0.85,
        ticket_price: 60.00,
        ticket_price_currency: "GBP",
        event_desc: "Electric Symphony, the dynamic DJ duo, electrifies crowds with pulsating beats and euphoric melodies. Prepare for a sonic journey as they blend genres promising an unforgettable night of music and energy.",
        event_image: "https://ik.imagekit.io/enxdlva/event-images/takemeout/wesley-tingey-Q5ugrfN4oHk-unsplash.jpg",
        event_image_attribution: "Wesley Tingey",
        event_image_attribution_link: "https://unsplash.com/@wesleyphotography?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash"
    },
    {
        id: "66327933-ce38-47e0-9bfe-5d29048bacae",
        event_name: "Crystal Harmony",
        event_date: "2025-05-18",
        venue_id: "d9ef9352-2367-4272-8884-70cf80cb7a38",
        start_time: "20:00:00",
        sell_through: 0.90,
        ticket_price: 55.00,
        ticket_price_currency: "GBP",
        event_desc: "Crystal Harmony merges folk and electronic, captivating with ethereal melodies and organic rhythms. A sonic journey where tradition meets innovation, resonating deeply within the soul.",
        event_image: "https://ik.imagekit.io/enxdlva/event-images/takemeout/valentin-lacoste-YII9O3qEz3s-unsplash.jpg",
        event_image_attribution: "Valentin Lacoste",
        event_image_attribution_link: "https://unsplash.com/@valentinlacoste?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash"
    },
    {
        id: "70ca48a6-93e2-4ff0-b3a2-f5a38f1a043e",
        event_name: "Reveries",
        event_date: "2025-06-22",
        venue_id: "a193a6a7-42ab-4182-97dc-555ee85e7486",
        start_time: "19:00:00",
        sell_through: 0.88,
        ticket_price: 65.00,
        ticket_price_currency: "GBP",
        event_desc: "Reveries invites listeners into a world of dreamy melodies and introspective lyrics. Join their sonic journey of self-discovery where every chord resonates with dreams and desires.",
        event_image: "https://ik.imagekit.io/enxdlva/event-images/takemeout/ana-grave-gHcWaeldgtQ-unsplash.jpg",
        event_image_attribution: "Ana Grave",
        event_image_attribution_link: "https://unsplash.com/@anagrave?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash"
    },
    {
        id: "e02f302a-c67c-4600-bf12-e364b59b80ea",
        event_name: "Strawberry Lemonade",
        event_date: "2025-08-15",
        venue_id: "bdc6bb69-e09c-498d-8abd-be2792504d00",
        start_time: "19:30:00",
        sell_through: 0.90,
        ticket_price: 60.00,
        ticket_price_currency: "GBP",
        event_desc: "Strawberry Lemonade infuses her performances with a refreshing blend of sweetness and zest. With a voice as vibrant as summer, she takes audiences on a tantalizing journey through melody.",
        event_image: "https://ik.imagekit.io/enxdlva/event-images/takemeout/Ombre%20Balloons.jpg",
        event_image_attribution: "Amy Shamblen",
        event_image_attribution_link: "https://unsplash.com/@amyshamblen?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash"
    },
    {
        id: "d3d7aa3c-6e27-4ab0-9496-f95faa5042f0",
        event_name: "Ellipsis",
        event_date: "2025-09-30",
        venue_id: "3ce124a4-78b0-4d80-91b9-11f9ced631a7",
        start_time: "20:00:00",
        sell_through: 0.85,
        ticket_price: 55.00,
        ticket_price_currency: "GBP",
        event_desc: "Ellipsis defies genres with ethereal soundscapes, blending dreamy melodies into intricate layers. Each performance invites a journey of introspection and emotion.",
        event_image: "https://ik.imagekit.io/enxdlva/event-images/takemeout/alexandre-st-louis-IlfpKwRMln0-unsplash.jpg?updatedAt=1711126482254",
        event_image_attribution: "Alexandre St-Louis",
        event_image_attribution_link: "https://unsplash.com/@alxstls?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash"
    },
    {
        id: "828c12d1-c0dd-4fd4-b8db-ac8eb493f8f8",
        event_name: "Cosmic Odyssey",
        event_date: "2025-10-25",
        venue_id: "8f16bd30-bab5-40af-aca2-b63d5fdd1acc",
        start_time: "20:30:00",
        sell_through: 0.88,
        ticket_price: 50.00,
        ticket_price_currency: "GBP",
        event_desc: "Cosmic Odyssey sparks stages with infectious pop-punk energy, blasting listeners into outer space with cosmic melodies and raw lyrics. Join the odyssey for anthems of rebellion and heartache.",
        event_image: "https://ik.imagekit.io/enxdlva/event-images/takemeout/wyanna-wenceslao-UBqwLun5RFU-unsplash.jpg",
        event_image_attribution: "Wyanna Wenceslao",
        event_image_attribution_link: "https://unsplash.com/@wenceyanna?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash"
    },
    {
        id: "b6abe52c-05be-4c90-b39a-d9decefd4274",
        event_name: "Ivy",
        event_date: "2026-01-25",
        venue_id: "83433026-ca32-4c6d-bd86-a39ee8b7303e",
        start_time: "20:30:00",
        sell_through: 0.90,
        ticket_price: 75.00,
        ticket_price_currency: "GBP",
        event_desc: "Ivy blends pop, rock, folk, and a sprinkle of magic into enchanting melodies. Her ethereal voice transports listeners to whimsical realms, promising a spellbinding experience that lingers.",
        event_image: "https://ik.imagekit.io/enxdlva/event-images/takemeout/vidar-nordli-mathisen-CTlRgg7Gfmw-unsplash.jpg",
        event_image_attribution: "Vidar Nordli-Mathisen",
        event_image_attribution_link: "https://unsplash.com/@vidarnm?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash"
    }
]
