
module.exports = [
    {
        id: 1,
        venue: "Massey Hall",
        venue_address: "178 Victoria St",
        venue_city: "Toronto",
        venue_state: "Ontario",
        venue_postal_code: "M5B 1T7",
        venue_country: "Canada",
        venue_email: "contactus@mh-rth.com",
        venue_latitude: 43.6544,
        venue_longitude: -79.3807,
        venue_likes: 0
    },
    {
        id: 2,
        venue: "L'Olympia",
        venue_address: "1004 St-Catherine East",
        venue_city: "Montreal",
        venue_state: "Quebec",
        venue_postal_code: "H2L 2G2",
        venue_country: "Canada",
        venue_email: "billetterie@olympiamontreal.com",
        venue_latitude: 45.5144,
        venue_longitude: -73.5628,
        venue_likes: 0
    },
    {
        id: 3,
        venue: "Scotiabank Centre",
        venue_address: "1800 Argyle St",
        venue_city: "Halifax",
        venue_state: "Nova Scotia",
        venue_postal_code: "B3J 2V9",
        venue_country: "Canada",
        venue_email: "info@scotiabank-centre.com",
        venue_latitude: 44.6498,
        venue_longitude: -63.5752,
        venue_likes: 0
    },
    {
        id: 4,
        venue: "Rogers Arena",
        venue_address: "800 Griffiths Way",
        venue_city: "Vancouver",
        venue_state: "British Columbia",
        venue_postal_code: "V6B 6G1",
        venue_country: "Canada",
        venue_email: "info@rogersarena.com",
        venue_latitude: 49.2774,
        venue_longitude: -123.1038,
        venue_likes: 0
    },
    {
        id: 5,
        venue: "Scotiabank Arena",
        venue_address: "40 Bay St",
        venue_city: "Toronto",
        venue_state: "Ontario",
        venue_postal_code: "M5J 2X2",
        venue_country: "Canada",
        venue_email: "info@scotiabankarena.com",
        venue_latitude: 43.6435,
        venue_longitude: -79.3791,
        venue_likes: 0
    },
    {
        id: 6,
        venue: "Bell MTS Place",
        venue_address: "300 Portage Ave",
        venue_city: "Winnipeg",
        venue_state: "Manitoba",
        venue_postal_code: "R3C 5S4",
        venue_country: "Canada",
        venue_email: "info@bellmtsplace.ca",
        venue_latitude: 49.8918,
        venue_longitude: -97.1444,
        venue_likes: 0
    },
    {
        id: 7,
        venue: "Canadian Tire Centre",
        venue_address: "1000 Palladium Dr",
        venue_city: "Ottawa",
        venue_state: "Ontario",
        venue_postal_code: "K2V 1A5",
        venue_country: "Canada",
        venue_email: "info@canadiantirecentre.com",
        venue_latitude: 45.2962,
        venue_longitude: -75.9276,
        venue_likes: 0
    },
    {
        id: 8,
        venue: "History",
        venue_address: "1663 Queen Street East",
        venue_city: "Toronto",
        venue_state: "Ontario",
        venue_postal_code: "M4L 1G5",
        venue_country: "Canada",
        venue_email: "info@scotiabankarena.com",
        venue_latitude: 43.6685,
        venue_longitude: -79.3244,
        venue_likes: 0
    },
    {
        id: 9,
        venue: "Vogue Theatre",
        venue_address: "918 Granville St",
        venue_city: "Vancouver",
        venue_state: "British Columbia",
        venue_postal_code: "V6Z 1L2",
        venue_country: "Canada",
        venue_email: "info@voguetheatre.com",
        venue_latitude: 49.2793,
        venue_longitude: -123.1224,
        venue_likes: 0
    },
    {
        id: 10,
        venue: "Brixton Academy",
        venue_address: "211 Stockwell Road",
        venue_city: "London",
        venue_state: "England",
        venue_postal_code: "SW9 9SL",
        venue_country: "United Kingdom",
        venue_email: "mail@o2academybrixton.co.uk",
        venue_latitude: 51.4659,
        venue_longitude: -0.1142,
        venue_likes: 0
    },
    {
        id: 11,
        venue: "Manchester Arena",
        venue_address: "Victoria Station, Hunts Bank",
        venue_city: "Manchester",
        venue_state: "England",
        venue_postal_code: "M3 1AR",
        venue_country: "United Kingdom",
        venue_email: "info@manchester-arena.com",
        venue_latitude: 53.4851,
        venue_longitude: -2.2468,
        venue_likes: 0
    },
    {
        id: 12,
        venue: "The O2 Arena",
        venue_address: "Peninsula Square",
        venue_city: "London",
        venue_state: "England",
        venue_postal_code: "SE10 0DX",
        venue_country: "United Kingdom",
        venue_email: "info@theo2.co.uk",
        venue_latitude: 51.5033,
        venue_longitude: 0.0037,
        venue_likes: 0
    },
    {
        id: 13,
        venue: "Motorpoint Arena Cardiff",
        venue_address: "Mary Ann St",
        venue_city: "Cardiff",
        venue_state: "Wales",
        venue_postal_code: "CF10 2EQ",
        venue_country: "United Kingdom",
        venue_email: "info@motorpointarenacardiff.co.uk",
        venue_latitude: 51.4783,
        venue_longitude: -3.1821,
        venue_likes: 0
    },
    {
        id: 14,
        venue: "The SSE Hydro",
        venue_address: "Exhibition Way",
        venue_city: "Glasgow",
        venue_state: "Scotland",
        venue_postal_code: "G3 8YW",
        venue_country: "United Kingdom",
        venue_email: "info@thessehydro.com",
        venue_latitude: 55.8609,
        venue_longitude: -4.2871,
        venue_likes: 0
    },
    {
        id: 15,
        venue: "SSE Arena, Belfast",
        venue_address: "2 Queens Quay",
        venue_city: "Belfast",
        venue_state: "Northern Ireland",
        venue_postal_code: "BT3 9QQ",
        venue_country: "United Kingdom",
        venue_email: "info@ssearenabelfast.com",
        venue_latitude: 54.6048,
        venue_longitude: -5.9176,
        venue_likes: 0
    },
    {
        id: 16,
        venue: "First Direct Arena",
        venue_address: "Arena Way",
        venue_city: "Leeds",
        venue_state: "England",
        venue_postal_code: "LS2 8BY",
        venue_country: "United Kingdom",
        venue_email: "info@firstdirectarena.com",
        venue_latitude: 53.8036,
        venue_longitude: -1.5489,
        venue_likes: 0
    },
    {
        id: 17,
        venue: "Utilita Arena Birmingham",
        venue_address: "King Edwards Rd",
        venue_city: "Birmingham",
        venue_state: "England",
        venue_postal_code: "B1 2AA",
        venue_country: "United Kingdom",
        venue_email: "info@arenabham.co.uk",
        venue_latitude: 52.479,
        venue_longitude: -1.91,
        venue_likes: 0
    }
]