
module.exports = [
    {
        id: "2922c286-16cd-4d43-ab98-c79f698aeab0",
        venue_name: "Roundhouse",
        venue_address: "Chalk Farm Rd",
        venue_city: "London",
        venue_state: "England",
        venue_postal_code: "NW1 8EH",
        venue_country: "United Kingdom",
        venue_latitude: 51.5423,
        venue_longitude: -0.1516,
        venue_email: "info@roundhouse.org.uk",
        venue_image: "",
        venue_image_attribution: "",
        venue_image_attribution_link: "",
        venue_likes: 0
    },
    {
        id: "5bf7bd6c-2b16-4129-bddc-9d37ff8539e9",
        venue_name: "Hammersmith Apollo",
        venue_address: "45 Queen Caroline St",
        venue_city: "London",
        venue_state: "England",
        venue_postal_code: "H2L 2G2",
        venue_country: "United Kingdom",
        venue_latitude: 51.4920,
        venue_longitude: -0.2238,
        venue_email: "info@eventimapollo.com",
        venue_image: "",
        venue_image_attribution: "",
        venue_image_attribution_link: "",
        venue_likes: 0
    },
    {
        id: "90ac3319-70d1-4a51-b91d-ba6c2464408c",
        venue_name: "Alexandra Palace",
        venue_address: "Alexandra Palace Way",
        venue_city: "London",
        venue_state: "England",
        venue_postal_code: "N22 7AY",
        venue_country: "United Kingdom",
        venue_latitude: 51.5900,
        venue_longitude: -0.1313,
        venue_email: "info@alexandrapalace.com",
        venue_image: "",
        venue_image_attribution: "",
        venue_image_attribution_link: "",
        venue_likes: 0
    },
    {
        id: "bfc9bea7-66f1-44e9-879b-4d363a888eb4",
        venue_name: "Albert Hall Manchester",
        venue_address: "27 Peter St",
        venue_city: "Manchester",
        venue_state: "England",
        venue_postal_code: "M2 5QR",
        venue_country: "United Kingdom",
        venue_latitude: 53.4776,
        venue_longitude: -2.2489,
        venue_email: "info@alberthallmanchester.com",
        venue_image: "",
        venue_image_attribution: "",
        venue_image_attribution_link: "",
        venue_likes: 0
    },
    {
        id: "89898957-04ba-4bd0-9f5c-a7aea7447963",
        venue_name: "SWX Bristol",
        venue_address: "15 Nelson St",
        venue_city: "Bristol",
        venue_state: "England",
        venue_postal_code: "BS1 2JY",
        venue_country: "United Kingdom",
        venue_latitude:  51.4553,
        venue_longitude: -2.5922,
        venue_email: "info@swxbristol.com",
        venue_image: "",
        venue_image_attribution: "",
        venue_image_attribution_link: "",
        venue_likes: 0
    },
    {
        id: "ade0a47b-cee6-4693-b4cd-a7e6cb25f4b7",
        venue_name: "O2 Academy Leeds",
        venue_address: "55 Cookridge St",
        venue_city: "Leeds",
        venue_state: "England",
        venue_postal_code: "LS2 3AW",
        venue_country: "United Kingdom",
        venue_latitude: 53.8006,
        venue_longitude: -1.5465,
        venue_email: "mail@o2academyleeds.co.uk",
        venue_image:"",
        venue_image_attribution: "",
        venue_image_attribution_link: "",
        venue_likes: 0
    },
    {
        id: "bb1491eb-30e6-4728-a5fa-72f89feaf622",
        venue_name: "O2 Institute Birmingham",
        venue_address: "78 Digbeth",
        venue_city: "Birmingham",
        venue_state: "England",
        venue_postal_code: "B5 6DY",
        venue_country: "United Kingdom",
        venue_latitude: 52.4744,
        venue_longitude: -1.8876,
        venue_email: "mail@o2institutebirmingham.co.uk",
        venue_image: "",
        venue_image_attribution: "",
        venue_image_attribution_link: "",
        venue_likes: 0
    },
    {
        id: "150a36cf-f38e-4f59-8e31-39974207372d",
        venue_name: "Barrowland Ballroom",
        venue_address: "244 Gallowgate",
        venue_city: "Glasgow",
        venue_state: "Scotland",
        venue_postal_code: "G4 0TT",
        venue_country: "United Kingdom",
        venue_latitude: 55.8575,
        venue_longitude: -4.2364,
        venue_email: "office@barrowland-ballroom.co.uk",
        venue_image: "",
        venue_image_attribution: "",
        venue_image_attribution_link: "",
        venue_likes: 0
    },
    {
        id: "9b4f79ea-0e6c-4e59-8e05-afd933d0b3d3",
        venue_name: "O2 Shepherd\’s Bush Empire",
        venue_address: "Shepherd\'s Bush Green",
        venue_city: "London",
        venue_state: "England",
        venue_postal_code: "W12 8TT",
        venue_country: "United Kingdom",
        venue_latitude: 51.5058,
        venue_longitude: -0.2256,
        venue_email: "info@o2shepherdsbushempire.co.uk",
        venue_image: "",
        venue_image_attribution: "",
        venue_image_attribution_link: "",
        venue_likes: 0
    },
    {
        id: "83433026-ca32-4c6d-bd86-a39ee8b7303e",
        venue_name: "Brixton Academy",
        venue_address: "211 Stockwell Road",
        venue_city: "London",
        venue_state: "England",
        venue_postal_code: "SW9 9SL",
        venue_country: "United Kingdom",
        venue_latitude: 51.4659,
        venue_longitude: -0.1142,
        venue_email: "mail@o2academybrixton.co.uk",
        venue_image: "https://ik.imagekit.io/enxdlva/venue-images/takemeout/ehimetalor-akhere-unuabona-Ks4QgxeHlm0-unsplash.jpg",
        venue_image_attribution: "Ehimetalor Akhere Unuabona",
        venue_image_attribution_link: "https://unsplash.com/@mettyunuabona?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash",
        venue_likes: 0
    },
    {
        id: "a193a6a7-42ab-4182-97dc-555ee85e7486",
        venue_name: "Manchester Arena",
        venue_address: "Victoria Station, Hunts Bank",
        venue_city: "Manchester",
        venue_state: "England",
        venue_postal_code: "M3 1AR",
        venue_country: "United Kingdom",
        venue_latitude: 53.4851,
        venue_longitude: -2.2468,
        venue_email: "info@manchester-arena.com",
        venue_image: "",
        venue_image_attribution: "",
        venue_image_attribution_link: "",
        venue_likes: 0
    },
    {
        id: "8f16bd30-bab5-40af-aca2-b63d5fdd1acc",
        venue_name: "The O2 Arena",
        venue_address: "Peninsula Square",
        venue_city: "London",
        venue_state: "England",
        venue_postal_code: "SE10 0DX",
        venue_country: "United Kingdom",
        venue_latitude: 51.5033,
        venue_longitude: 0.0037,
        venue_email: "info@theo2.co.uk",
        venue_image: "https://ik.imagekit.io/enxdlva/venue-images/takemeout/k-howard-dHXTMqkeGNM-unsplash.jpg",
        venue_image_attribution: "K HOWARD",
        venue_image_attribution_link: "https://unsplash.com/@kwh101?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash",
        venue_likes: 0
    },
    {
        id: "bdc6bb69-e09c-498d-8abd-be2792504d00",
        venue_name: "Motorpoint Arena Cardiff",
        venue_address: "Mary Ann St",
        venue_city: "Cardiff",
        venue_state: "Wales",
        venue_postal_code: "CF10 2EQ",
        venue_country: "United Kingdom",
        venue_latitude: 51.4783,
        venue_longitude: -3.1821,
        venue_email: "info@motorpointarenacardiff.co.uk",
        venue_image: "",
        venue_image_attribution: "",
        venue_image_attribution_link: "",
        venue_likes: 0
    },
    {
        id: "3ce124a4-78b0-4d80-91b9-11f9ced631a7",
        venue_name: "The SSE Hydro",
        venue_address: "Exhibition Way",
        venue_city: "Glasgow",
        venue_state: "Scotland",
        venue_postal_code: "G3 8YW",
        venue_country: "United Kingdom",
        venue_latitude: 55.8609,
        venue_longitude: -4.2871,
        venue_email: "info@thessehydro.com",
        venue_image: "https://ik.imagekit.io/enxdlva/venue-images/takemeout/carina-m-OmOlENGIWks-unsplash.jpg",
        venue_image_attribution: "carina. m",
        venue_image_attribution_link: "https://unsplash.com/@oranje?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash",
        venue_likes: 0
    },
    {
        id: "4dd464d6-90b8-4330-91e0-bd1217811bd9",
        venue_name: "Bristol Beacon",
        venue_address: "Trenchard Street",
        venue_city: "Bristol",
        venue_state: "England",
        venue_postal_code: "BS1 5AR",
        venue_country: "United Kingdom",
        venue_latitude: 51.45451,
        venue_longitude: -2.59823,
        venue_email: "hello@bristolbeacon.org",
        venue_image: "",
        venue_image_attribution: "",
        venue_image_attribution_link: "",
        venue_likes: 0
    },
    {
        id: "c0ba64a8-0ecb-4a7d-ab7f-2dbbd1d437b1",
        venue_name: "First Direct Arena",
        venue_address: "Arena Way",
        venue_city: "Leeds",
        venue_state: "England",
        venue_postal_code: "LS2 8BY",
        venue_country: "United Kingdom",
        venue_latitude: 53.8036,
        venue_longitude: -1.5489,
        venue_email: "info@firstdirectarena.com",
        venue_image: "",
        venue_image_attribution: "",
        venue_image_attribution_link: "",
        venue_likes: 0
    },
    {
        id: "d9ef9352-2367-4272-8884-70cf80cb7a38",
        venue_name: "Utilita Arena Birmingham",
        venue_address: "King Edwards Rd",
        venue_city: "Birmingham",
        venue_state: "England",
        venue_postal_code: "B1 2AA",
        venue_country: "United Kingdom",
        venue_latitude: 52.479,
        venue_longitude: -1.91,
        venue_email: "info@arenabham.co.uk",
        venue_image: "",
        venue_image_attribution: "",
        venue_image_attribution_link: "",
        venue_likes: 0
    }
]